/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.crtp.slf4j.utilities;

import io.crtp.slf4j.list.LinkedList;

public class StringUtils {
    public static String join(LinkedList source) {
        return JoinUtils.join(source);
    }

    public static LinkedList split(String source) {
        return SplitUtils.split(source);
    }
}
