/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.crtp.slf4j.app;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import java.util.Date;

public class App {

    private static final Logger logger = LoggerFactory.getLogger(App.class);

    public static void main(String[] args) {
        //LinkedList tokens;
        //tokens = split(getMessage());
        //String result = join(tokens);
        //System.out.println(WordUtils.capitalize(result));
        logger.debug("[MAIN] Current Date: {}",getCurrentDate());
    }

    private static Date getCurrentDate() {
        return new Date();
    }
}
